include::_include_all.adoc[]
[[Ch01_TermsOfUse]]
[suppress='JapaneseStyle']
= Terms of Use

In order to use this document, you are required to agree to abide by the following terms. If you do not agree with the terms, you must immediately delete or destroy this document and all its duplicate copies.

. Copyrights and all other rights of this document shall belong to NTT DATA or third party possessing such rights.

. This document may be reproduced, translated or adapted, in whole or in part for personal use. However, deletion of the terms given on this page and copyright notice of NTT DATA is prohibited.

. This document may be changed, in whole or in part for personal use. Creation of secondary work using this document is allowed. However, “Reference document: TERASOLUNA Batch Framework for Java (5.x) Development Guideline” or equivalent documents may be mentioned in created document and its duplicate copies.

. Document and its duplicate copies created according to Clause 2 may be provided to third party only if these are free of cost.

. Use of this document and its duplicate copies, and transfer of rights of this contract to a third party, in whole or in part, beyond the conditions specified in this contract, are prohibited without the written consent of NTT Data.

. NTT DATA shall not bear any responsibility regarding correctness of contents of this document, warranty of fitness for usage purpose, assurance for accuracy and reliability of usage result, liability for defect warranty, and any damage incurred directly or indirectly.

. NTT DATA does not guarantee the infringement of copyrights and any other rights of third party through this document. In addition to this, NTT DATA shall not bear any responsibility regarding any claim (Including the claims occurred due to dispute with third party) occurred directly or indirectly due to infringement of copyright and other rights.

This document is created by referring to Macchinetta "Reference document：Macchinetta Batch Framework Development Guideline".

Registered trademarks or trademarks of company name and service name, and product name of their respective companies used in this document are as follows.

* TERASOLUNA is a registered trademark of NTT DATA Corporation.
* Macchinetta is the registered trademark of NTT.
* All other company names and product names are the registered trademarks or trademarks of their respective companies.

== Reference

===  Macchinetta-Terms of use

In order to use this document, you are required to agree to abide by the following terms. If you do not agree with the terms, you must immediately delete or destroy this document and all its duplicate copies.

. Copyrights and all other rights of this document shall belong to Nippon Telegraph and Telephone Corporation (hereinafter referred to as "NTT")  or third party possessing such rights.

.  This document may be reproduced, translated or adapted, in whole or in part for personal use. However, deletion of the terms given on this page and copyright notice of NTT is prohibited.

. This document may be changed, in whole or in part for personal use. Creation of secondary work using this document is allowed. However, “Reference document: Macchinetta Batch Framework Development Guideline” or equivalent documents may be mentioned in created document and its duplicate copies.

. Document and its duplicate copies created according to Clause 2 may be provided to third party only if these are open source and free softwares, it is available.

. Use of this document and its duplicate copies, and transfer of rights of this contract to a third party, in whole or in part, beyond the conditions specified in this contract, are prohibited without the written consent of NTT.

. NTT shall not bear any responsibility regarding correctness of contents of this document, warranty of fitness for usage purpose, assurance for accuracy and reliability of usage result, liability for defect warranty, and any damage incurred directly or indirectly.

. NTT does not guarantee the infringement of copyrights and any other rights of third party through this document. In addition to this, NTT shall not bear any responsibility regarding any claim (Including the claims occurred due to dispute with third party) occurred directly or indirectly due to infringement of copyright and other rights.

Registered trademarks or trademarks of company name and service name, and product name of their respective companies used in this document are as follows.

* Macchinetta is the registered trademark of NTT.
* All other company names and product names are the registered trademarks or trademarks of their respective companies.
